# Site settings
title: KAMOJANG
email: voltus5@gmail.com
description: "MAYDAY.US - A Crowdfunded, Kickstarted SuperPAC to end all SuperPACs"
baseurl: ''

# Build settings
encoding: utf-8
markdown: kramdown
permalink: pretty
exclude: [old]

# Blog & RSS settings
name: Mayday PAC Blog
url: http://rullyvm.github.io
